version: '3'

services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./client-gateway/src
    #       target: /usr/src/app/src
    #       ignore:
    #         - node_modules/**
    #     - action: rebuild
    #       path: package.json
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
  
  # products-ms:
  #   build: ./products-ms
  #   volumes:
  #     - ./products-ms/src:/usr/src/app/src
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev
  #   # develop:
  #   #   watch:
  #   #     - action: sync+restart
  #   #       path: ./products-ms/src
  #   #       target: /usr/src/app/src
  #   #       ignore:
  #   #         - node_modules/**
  #   #     - action: rebuild
  #   #       path: package.json
  #   environment:
  #     - PORT=3001
  #     - NATS_SERVERS=${NATS_SERVERS}
  #     - DATABASE_URL=file:./dev.db

  # orders-ms:
  #   depends_on:
  #     - orders-db
  #   build: ./orders-ms
  #   volumes:
  #     - ./orders-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   # develop:
  #   #   watch:
  #   #     - action: sync+restart
  #   #       path: ./orders-ms/src
  #   #       target: /usr/src/app/src
  #   #       ignore:
  #   #         - node_modules/**
  #   #     - action: rebuild
  #   #       path: package.json
  #   environment:
  #     - PORT=3002
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public

  # orders-db:
    # container_name: orders_database
    # image: postgres:16.2
    # restart: always
    # volumes:
    #   - ./orders-ms/postgres:/var/lib/postgresql/data
    # ports:
    #   - 5433:5432
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=123456
    #   - POSTGRES_DB=ordersdb

#  ==============================
#  =       Payments MS       =
#  ==============================
  # payments-ms:
  #   container_name: payments-ms
  #   build: ./payments-ms
  #   volumes:
  #     - ./payments-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   # develop:
  #   #   watch:
  #   #     - action: sync+restart
  #   #       path: ./payments-ms/src
  #   #       target: /usr/src/app/src
  #   #       ignore:
  #   #         - node_modules/**
  #   #     - action: rebuild
  #   #       path: package.json
  #   ports:
  #     - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
  #   environment:
  #     - PORT=${PAYMENTS_MS_PORT}
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - STRIPE_SECRET=${STRIPE_SECRET}
  #     - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
  #     - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
  #     - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

#  ==============================
#  =       Auth MS       =
#  ==============================
  auth-ms:
    container_name: auth-ms
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}