name: CI/CD Products Microservice

on:
  push:
    branches:
      - "main"
    paths:
      - "products-ms/**"

jobs:
  call_build_and_push:
    uses: ./.github/workflows/build-microservice.yml
    with:
      service_name: jhordanfw/image-ms-registry:products-ms
      dockerfile_path: products-ms/dockerfile.prod
    secrets: inherit
